import { db, Platform, Subject, Topic, Roadmap } from 'astro:db';
import topicsData from './topics.json';
import roadmapsData from './roadmaps.json';

type TopicJson = {
  id: number;
  platform_id: number;
  subject_id: number;
  name: string;
  is_active: boolean;
  q_count?: number;
};

type RoadmapJson = {
  id: number;
  platform_id: number;
  subject_id: number;
  topic_id: number;
  name: string;
  is_active: boolean;
  q_count?: number;
};

// https://astro.build/db/seed
export async function seedQuiz() {
  console.log('Seeding quiz data...');
	await db.insert(Platform).values([
    {
      id: 1,
      name: "Medical",
      description: "Explore medicine, health science, and diagnostics.",
      isActive: true,
      icon: "fa-heartbeat",
      type: "A",
      qCount: 39519,
    },
    {
      id: 2,
      name: "Engineering",
      description: "Explore concepts and disciplines in engineering.",
      isActive: true,
      icon: "fa-cogs",
      type: "P",
      qCount: 21082,
    },
    {
      id: 3,
      name: "Law",
      description: "Understand legal systems, laws, and judiciary concepts.",
      isActive: true,
      icon: "fa-gavel",
      type: "P",
      qCount: 23100,
    },
    {
      id: 4,
      name: "Finance",
      description: "Learn financial planning, markets, and investments.",
      isActive: true,
      icon: "fa-money-bill",
      type: "P",
      qCount: 20949,
    },
    {
      id: 5,
      name: "Driving",
      description: "Practice theory and rules for driving tests.",
      isActive: true,
      icon: "fa-car",
      type: "A",
      qCount: 42338,
    },
    {
      id: 6,
      name: "Government Exams",
      description: "Prepare for various competitive government exams.",
      isActive: true,
      icon: "fa-building",
      type: "A",
      qCount: 26053,
    },
    {
      id: 7,
      name: "Logical Reasoning",
      description: "Sharpen logical thinking and analytical reasoning.",
      isActive: true,
      icon: "fa-brain",
      type: "A",
      qCount: 21373,
    },
    {
      id: 8,
      name: "Mathematics",
      description: "Learn mathematics concepts from basics to advanced.",
      isActive: true,
      icon: "fa-square-root-alt",
      type: "P",
      qCount: 22556,
    },
    {
      id: 9,
      name: "Banking",
      description: "Explore banking services, finance, and operations.",
      isActive: true,
      icon: "fa-flask",
      type: "A",
      qCount: 20818,
    },
    {
      id: 10,
      name: "History",
      description: "Explore major historical events and civilizations.",
      isActive: true,
      icon: "fa-history",
      type: "A",
      qCount: 20709,
    },
    {
      id: 11,
      name: "Geography",
      description: "Study earth’s physical features and human geography.",
      isActive: true,
      icon: "fa-globe-americas",
      type: "A",
      qCount: 23646,
    },
    {
      id: 12,
      name: "Programming",
      description: "Master programming languages and software development.",
      isActive: true,
      icon: "fa-laptop-code",
      type: "P",
      qCount: 196987,
    },
    {
      id: 13,
      name: "Soft Skills",
      description: "Enhance communication, empathy, and people skills.",
      isActive: true,
      icon: "fa-users",
      type: "A",
      qCount: 26794,
    },
    {
      id: 14,
      name: "Language Tests",
      description: "Get ready for global language proficiency exams.",
      isActive: true,
      icon: "fa-comments",
      type: "P",
      qCount: 27363,
    },
    {
      id: 15,
      name: "Business",
      description: "Master business concepts, operations, and strategy.",
      isActive: true,
      icon: "fa-briefcase",
      type: "P",
      qCount: 39357,
    },
    {
      id: 16,
      name: "IT Certifications",
      description: "Prepare for globally recognized IT certification exams.",
      isActive: true,
      icon: "fa-certificate",
      type: "P",
      qCount: 24690,
    },
    {
      id: 17,
      name: "Marketing",
      description: "Develop marketing strategies, branding, and sales skills.",
      isActive: true,
      icon: "fa-bullhorn",
      type: "P",
      qCount: 25071,
    },
    {
      id: 18,
      name: "Physics",
      description: "Understand physics laws and real-world applications.",
      isActive: true,
      icon: "fa-atom",
      type: "A",
      qCount: 22246,
    },
    {
      id: 19,
      name: "Chemistry",
      description: "Master chemical principles and reactions.",
      isActive: true,
      icon: "fa-flask",
      type: "A",
      qCount: 21490,
    },
    {
      id: 20,
      name: "Biology",
      description: "Study the structure, function, and behavior of living organisms.",
      isActive: true,
      icon: "fa-dna",
      type: "A",
      qCount: 21881,
    },
    {
      id: 24,
      name: "General Knowledge",
      description: "Expand your general knowledge across various topics.",
      isActive: true,
      icon: "fa-lightbulb",
      type: "A",
      qCount: 30966,
    },
    {
      id: 29,
      name: "Testing",
      description: "Assess your knowledge through test-based quizzes.",
      isActive: true,
      icon: "fa-vial",
      type: "P",
      qCount: 37531,
    },
    {
      id: 30,
      name: "Entertainment",
      description: "Quiz yourself on movies, music, gaming, and sports.",
      isActive: true,
      icon: "fas fa-film",
      type: "P",
      qCount: 28087,
    },
    {
      id: 31,
      name: "Environmental Science",
      description: "Understand ecosystems, sustainability, and global issues.",
      isActive: true,
      icon: "fa-leaf",
      type: "A",
      qCount: 26672,
    },
    {
      id: 32,
      name: "Arts & Humanities",
      description: "Dive into arts, culture, literature, and philosophy.",
      isActive: true,
      icon: "fa-palette",
      type: "A",
      qCount: 76848,
    },
    {
      id: 33,
      name: "Travel & Tourism",
      description: "Explore destinations, travel tips, and tourism management.",
      isActive: true,
      icon: "fa-plane",
      type: "P",
      qCount: 22591,
    },
    {
      id: 34,
      name: "Psychology",
      description: "Study the mind, behavior, and mental health theories.",
      isActive: true,
      icon: "fa-user-nurse",
      type: "A",
      qCount: 21173,
    },
    {
      id: 35,
      name: "Mechanical Skills",
      description: "Learn about tools, machines, engines, and mechanics.",
      isActive: true,
      icon: "fa-wrench",
      type: "P",
      qCount: 21316,
    },
    {
      id: 36,
      name: "Culture & Mythology",
      description: "Explore ancient myths, folklore, and cultural heritage.",
      isActive: true,
      icon: "fa-landmark",
      type: "A",
      qCount: 22332,
    },
    {
      id: 37,
      name: "Education & Teaching",
      description: "Focus on teaching strategies, pedagogy, and education systems.",
      isActive: true,
      icon: "fa-chalkboard-teacher",
      type: "P",
      qCount: 20870,
    },
    {
      id: 38,
      name: "Networking",
      description: "Learn about networking protocols, security, and systems.",
      isActive: true,
      icon: "fa-network-wired",
      type: "P",
      qCount: 22752,
    },
    {
      id: 39,
      name: "Ethics and Philosophy",
      description: "Explore moral philosophy, logic, and critical reasoning.",
      isActive: true,
      icon: "fa-balance-scale",
      type: "A",
      qCount: 28203,
    },
    {
      id: 40,
      name: "Astronomy & Space",
      description: "Learn about planets, galaxies, space exploration, and the universe.",
      isActive: true,
      icon: "fa-satellite-dish",
      type: "A",
      qCount: 20983,
    },
    {
      id: 41,
      name: "Economics",
      description: "Understand economic theories, markets, trade, and global development.",
      isActive: true,
      icon: "fa-chart-line",
      type: "A",
      qCount: 22768,
    },
    {
      id: 42,
      name: "Languages & Literature",
      description: "Dive into grammar, prose, poetry, world literature, and comprehension.",
      isActive: true,
      icon: "fa-book-open",
      type: "A",
      qCount: 23633,
    },
    {
      id: 43,
      name: "Health & Nutrition",
      description: "Focus on wellness, dietary habits, exercise, and preventive care.",
      isActive: true,
      icon: "fa-apple-alt",
      type: "A",
      qCount: 20604,
    },
    {
      id: 44,
      name: "Ethical Hacking & Cybersecurity",
      description: "Learn about penetration testing, threat mitigation, and cyber protection.",
      isActive: true,
      icon: "fa-user-secret",
      type: "P",
      qCount: 21061,
    },
    {
      id: 45,
      name: "Civics & Governance",
      description: "Understand political systems, constitutional law, and civic responsibilities.",
      isActive: true,
      icon: "fa-landmark",
      type: "A",
      qCount: 36815,
    },
    {
      id: 46,
      name: "Wellness & Lifestyle",
      description: "Improve mental and physical well-being through mindfulness and healthy living.",
      isActive: true,
      icon: "fa-spa",
      type: "A",
      qCount: 111147,
    },
    {
      id: 47,
      name: "Quantitative Aptitude",
      description: "Master arithmetic and problem-solving for competitive exams.",
      isActive: true,
      icon: "fa-divide",
      type: "A",
      qCount: 56896,
    },
    {
      id: 48,
      name: "Culinary Arts",
      description: "Learn cooking methods, nutrition, and kitchen safety.",
      isActive: true,
      icon: "fa-utensils",
      type: "P",
      qCount: 27877,
    },
    {
      id: 49,
      name: "Architecture & Urban Planning",
      description: "Design spaces and understand the principles of urban development.",
      isActive: false,
      icon: "fa-drafting-compass",
      type: "P",
      qCount: 0,
    },
    {
      id: 50,
      name: "Design & UX",
      description: "Create user-centered digital experiences and visual designs.",
      isActive: false,
      icon: "fa-paint-brush",
      type: "P",
      qCount: 0,
    },
    {
      id: 51,
      name: "Higher Education Prep",
      description: "Prepare for GRE, GMAT, TOEFL, IELTS, and other academic exams.",
      isActive: false,
      icon: "fa-university",
      type: "P",
      qCount: 0,
    },
    {
      id: 52,
      name: "Game Design & Theory",
      description: "Understand game mechanics, user psychology, and development tools.",
      isActive: false,
      icon: "fa-gamepad",
      type: "P",
      qCount: 0,
    },
    {
      id: 53,
      name: "School",
      description: "Quiz content aligned with Indian school syllabi across various state and national boards for SSLC, +1, and +2 levels.",
      isActive: true,
      icon: "fa-school",
      type: "A",
      qCount: 59374,
    },
  ]);

  await db.insert(Subject).values([
      {
        id: 669,
        platformId: 39,
        name: "Logic & Critical Thinking",
        isActive: true,
        qCount: 3733,
      },
      {
        id: 670,
        platformId: 39,
        name: "Metaphysics",
        isActive: true,
        qCount: 4866,
      },
      {
        id: 671,
        platformId: 39,
        name: "Philosophy of Religion",
        isActive: true,
        qCount: 4481,
      },
      {
        id: 672,
        platformId: 39,
        name: "Aesthetics",
        isActive: true,
        qCount: 4815,
      },
      {
        id: 655,
        platformId: 47,
        name: "Arithmetic",
        isActive: true,
        qCount: 9034,
      },
      {
        id: 656,
        platformId: 47,
        name: "Algebra",
        isActive: true,
        qCount: 4969,
      },
      {
        id: 657,
        platformId: 47,
        name: "Geometry",
        isActive: true,
        qCount: 5393,
      },
      {
        id: 658,
        platformId: 47,
        name: "Mensuration",
        isActive: true,
        qCount: 3305,
      },
      {
        id: 659,
        platformId: 47,
        name: "Trigonometry",
        isActive: true,
        qCount: 2557,
      },
      {
        id: 660,
        platformId: 47,
        name: "Probability",
        isActive: true,
        qCount: 2399,
      },
      {
        id: 661,
        platformId: 47,
        name: "Statistics & Data Interpretation",
        isActive: true,
        qCount: 5724,
      },
      {
        id: 662,
        platformId: 47,
        name: "Number System",
        isActive: true,
        qCount: 3663,
      },
      {
        id: 663,
        platformId: 47,
        name: "Permutations & Combinations",
        isActive: true,
        qCount: 3328,
      },
      {
        id: 664,
        platformId: 47,
        name: "Time, Speed & Distance",
        isActive: true,
        qCount: 3784,
      },
      {
        id: 665,
        platformId: 47,
        name: "Time & Work",
        isActive: true,
        qCount: 2197,
      },
      {
        id: 666,
        platformId: 47,
        name: "Ratio & Proportion",
        isActive: true,
        qCount: 2338,
      },
      {
        id: 667,
        platformId: 47,
        name: "Percentages & Profit & Loss",
        isActive: true,
        qCount: 4355,
      },
      {
        id: 668,
        platformId: 47,
        name: "Simple & Compound Interest",
        isActive: true,
        qCount: 3850,
      },
      {
        id: 654,
        platformId: 15,
        name: "Salesforce",
        isActive: true,
        qCount: 21078,
      },
      {
        id: 649,
        platformId: 48,
        name: "Fundamentals of Cooking",
        isActive: true,
        qCount: 4655,
      },
      {
        id: 650,
        platformId: 48,
        name: "Cuisines of the World",
        isActive: true,
        qCount: 7613,
      },
      {
        id: 651,
        platformId: 48,
        name: "Nutrition & Dietetics",
        isActive: true,
        qCount: 5511,
      },
      {
        id: 652,
        platformId: 48,
        name: "Baking & Pastry Arts",
        isActive: true,
        qCount: 5923,
      },
      {
        id: 653,
        platformId: 48,
        name: "Food Presentation & Service",
        isActive: true,
        qCount: 4175,
      },
      {
        id: 1,
        platformId: 12,
        name: "Web Development",
        isActive: true,
        qCount: 21508,
      },
      {
        id: 11,
        platformId: 7,
        name: "Verbal Reasoning",
        isActive: true,
        qCount: 4482,
      },
      {
        id: 12,
        platformId: 7,
        name: "Non-Verbal Reasoning",
        isActive: true,
        qCount: 4206,
      },
      {
        id: 13,
        platformId: 7,
        name: "Analytical Reasoning",
        isActive: true,
        qCount: 5099,
      },
      {
        id: 14,
        platformId: 7,
        name: "Critical Thinking",
        isActive: true,
        qCount: 4191,
      },
      {
        id: 15,
        platformId: 7,
        name: "Puzzles & Brain Teasers",
        isActive: true,
        qCount: 3395,
      },
      {
        id: 16,
        platformId: 16,
        name: "Cloud Computing",
        isActive: true,
        qCount: 3943,
      },
      {
        id: 17,
        platformId: 16,
        name: "Cybersecurity",
        isActive: true,
        qCount: 3139,
      },
      {
        id: 18,
        platformId: 16,
        name: "Networking",
        isActive: true,
        qCount: 2887,
      },
      {
        id: 74,
        platformId: 15,
        name: "Marketing",
        isActive: true,
        qCount: 3654,
      },
      {
        id: 529,
        platformId: 40,
        name: "Cosmology",
        isActive: true,
        qCount: 4653,
      },
      {
        id: 530,
        platformId: 40,
        name: "Space Missions",
        isActive: true,
        qCount: 6430,
      },
      {
        id: 535,
        platformId: 42,
        name: "English Grammar",
        isActive: true,
        qCount: 6402,
      },
      {
        id: 536,
        platformId: 42,
        name: "World Literature",
        isActive: true,
        qCount: 6747,
      },
      {
        id: 537,
        platformId: 42,
        name: "Poetry and Prose",
        isActive: true,
        qCount: 5550,
      },
      {
        id: 538,
        platformId: 42,
        name: "Reading Comprehension",
        isActive: true,
        qCount: 4934,
      },
      {
        id: 543,
        platformId: 44,
        name: "Ethical Hacking Basics",
        isActive: true,
        qCount: 5393,
      },
      {
        id: 544,
        platformId: 44,
        name: "Web Application Security",
        isActive: true,
        qCount: 4419,
      },
      {
        id: 546,
        platformId: 44,
        name: "Cyber Law and Ethics",
        isActive: true,
        qCount: 5200,
      },
      {
        id: 54,
        platformId: 8,
        name: "Algebra",
        isActive: true,
        qCount: 4551,
      },
      {
        id: 196,
        platformId: 33,
        name: "Travel Planning",
        isActive: true,
        qCount: 4458,
      },
      {
        id: 3,
        platformId: 12,
        name: "Data Structures & Algorithms",
        isActive: true,
        qCount: 9378,
      },
      {
        id: 85,
        platformId: 17,
        name: "Marketing Fundamentals",
        isActive: true,
        qCount: 6334,
      },
      {
        id: 86,
        platformId: 17,
        name: "Digital Marketing",
        isActive: true,
        qCount: 6723,
      },
      {
        id: 197,
        platformId: 33,
        name: "Hospitality Management",
        isActive: true,
        qCount: 4669,
      },
      {
        id: 73,
        platformId: 15,
        name: "Management",
        isActive: true,
        qCount: 5286,
      },
      {
        id: 87,
        platformId: 17,
        name: "Social Media Marketing",
        isActive: true,
        qCount: 6733,
      },
      {
        id: 198,
        platformId: 33,
        name: "World Cultures",
        isActive: true,
        qCount: 4989,
      },
      {
        id: 199,
        platformId: 33,
        name: "Tourism Geography",
        isActive: true,
        qCount: 4143,
      },
      {
        id: 200,
        platformId: 34,
        name: "General Psychology",
        isActive: true,
        qCount: 3171,
      },
      {
        id: 201,
        platformId: 34,
        name: "Developmental Psychology",
        isActive: true,
        qCount: 4170,
      },
      {
        id: 202,
        platformId: 34,
        name: "Abnormal Psychology",
        isActive: true,
        qCount: 5537,
      },
      {
        id: 203,
        platformId: 34,
        name: "Social Psychology",
        isActive: true,
        qCount: 4109,
      },
      {
        id: 65,
        platformId: 13,
        name: "Communication Skills",
        isActive: true,
        qCount: 7712,
      },
      {
        id: 66,
        platformId: 13,
        name: "Leadership Skills",
        isActive: true,
        qCount: 6159,
      },
      {
        id: 68,
        platformId: 13,
        name: "Time Management",
        isActive: true,
        qCount: 6447,
      },
      {
        id: 531,
        platformId: 41,
        name: "Microeconomics",
        isActive: true,
        qCount: 6914,
      },
      {
        id: 532,
        platformId: 41,
        name: "Macroeconomics",
        isActive: true,
        qCount: 4808,
      },
      {
        id: 19,
        platformId: 16,
        name: "Software Development",
        isActive: true,
        qCount: 3490,
      },
      {
        id: 75,
        platformId: 15,
        name: "Finance",
        isActive: true,
        qCount: 4769,
      },
      {
        id: 76,
        platformId: 15,
        name: "Entrepreneurship",
        isActive: true,
        qCount: 4570,
      },
      {
        id: 533,
        platformId: 41,
        name: "International Trade",
        isActive: true,
        qCount: 5781,
      },
      {
        id: 4,
        platformId: 12,
        name: "Databases",
        isActive: true,
        qCount: 40848,
      },
      {
        id: 5,
        platformId: 12,
        name: "Cybersecurity",
        isActive: true,
        qCount: 5175,
      },
      {
        id: 6,
        platformId: 12,
        name: "Cloud Computing",
        isActive: true,
        qCount: 8388,
      },
      {
        id: 145,
        platformId: 24,
        name: "Geography",
        isActive: true,
        qCount: 2098,
      },
      {
        id: 146,
        platformId: 24,
        name: "Science",
        isActive: true,
        qCount: 2919,
      },
      {
        id: 46,
        platformId: 4,
        name: "Investment Management",
        isActive: true,
        qCount: 3838,
      },
      {
        id: 48,
        platformId: 4,
        name: "Risk Management",
        isActive: true,
        qCount: 2836,
      },
      {
        id: 49,
        platformId: 5,
        name: "Road Signs and Signals",
        isActive: true,
        qCount: 7025,
      },
      {
        id: 50,
        platformId: 5,
        name: "Traffic Rules and Regulations",
        isActive: true,
        qCount: 8314,
      },
      {
        id: 42,
        platformId: 2,
        name: "Core Engineering Subjects",
        isActive: true,
        qCount: 8300,
      },
      {
        id: 32,
        platformId: 3,
        name: "Corporate Law",
        isActive: true,
        qCount: 3934,
      },
      {
        id: 30,
        platformId: 3,
        name: "Law Entrance Exams",
        isActive: true,
        qCount: 3733,
      },
      {
        id: 206,
        platformId: 35,
        name: "Automobile Technology",
        isActive: true,
        qCount: 4869,
      },
      {
        id: 27,
        platformId: 6,
        name: "Defence Exams",
        isActive: true,
        qCount: 3864,
      },
      {
        id: 28,
        platformId: 6,
        name: "State Government Exams",
        isActive: true,
        qCount: 3206,
      },
      {
        id: 29,
        platformId: 6,
        name: "Teaching Eligibility Tests",
        isActive: true,
        qCount: 3790,
      },
      {
        id: 31,
        platformId: 3,
        name: "Judiciary Exams",
        isActive: true,
        qCount: 3347,
      },
      {
        id: 33,
        platformId: 3,
        name: "Constitutional Law",
        isActive: true,
        qCount: 3375,
      },
      {
        id: 34,
        platformId: 3,
        name: "Criminal Law",
        isActive: true,
        qCount: 4941,
      },
      {
        id: 35,
        platformId: 3,
        name: "International Law",
        isActive: true,
        qCount: 3770,
      },
      {
        id: 43,
        platformId: 2,
        name: "Specialized Engineering Fields",
        isActive: true,
        qCount: 8677,
      },
      {
        id: 36,
        platformId: 1,
        name: "Medical Entrance Exams",
        isActive: true,
        qCount: 4183,
      },
      {
        id: 37,
        platformId: 1,
        name: "Pre-Clinical Subjects",
        isActive: true,
        qCount: 3613,
      },
      {
        id: 38,
        platformId: 1,
        name: "Para-Clinical Subjects",
        isActive: true,
        qCount: 4347,
      },
      {
        id: 39,
        platformId: 1,
        name: "Clinical Subjects",
        isActive: true,
        qCount: 8919,
      },
      {
        id: 40,
        platformId: 1,
        name: "Medical Specializations",
        isActive: true,
        qCount: 7348,
      },
      {
        id: 41,
        platformId: 2,
        name: "Engineering Entrance Exams",
        isActive: true,
        qCount: 4105,
      },
      {
        id: 44,
        platformId: 4,
        name: "Financial Markets and Instruments",
        isActive: true,
        qCount: 5048,
      },
      {
        id: 67,
        platformId: 13,
        name: "Team Work",
        isActive: true,
        qCount: 6476,
      },
      {
        id: 7,
        platformId: 12,
        name: "DevOps",
        isActive: true,
        qCount: 6260,
      },
      {
        id: 51,
        platformId: 5,
        name: "Vehicle Operation and Control",
        isActive: true,
        qCount: 9005,
      },
      {
        id: 52,
        platformId: 5,
        name: "Safety Procedures and Emergency Handling",
        isActive: true,
        qCount: 9303,
      },
      {
        id: 53,
        platformId: 5,
        name: "Environmental Impact and Eco-driving",
        isActive: true,
        qCount: 8691,
      },
      {
        id: 55,
        platformId: 8,
        name: "Geometry",
        isActive: true,
        qCount: 4661,
      },
      {
        id: 56,
        platformId: 8,
        name: "Calculus",
        isActive: true,
        qCount: 5045,
      },
      {
        id: 57,
        platformId: 8,
        name: "Probability",
        isActive: true,
        qCount: 4629,
      },
      {
        id: 24,
        platformId: 6,
        name: "Banking Exams",
        isActive: true,
        qCount: 3442,
      },
      {
        id: 147,
        platformId: 24,
        name: "Sports",
        isActive: true,
        qCount: 2677,
      },
      {
        id: 148,
        platformId: 24,
        name: "Politics",
        isActive: true,
        qCount: 1721,
      },
      {
        id: 527,
        platformId: 40,
        name: "Solar System Exploration",
        isActive: true,
        qCount: 5321,
      },
      {
        id: 528,
        platformId: 40,
        name: "Stars and Galaxies",
        isActive: true,
        qCount: 4579,
      },
      {
        id: 545,
        platformId: 44,
        name: "Network Securities",
        isActive: true,
        qCount: 6049,
      },
      {
        id: 138,
        platformId: 14,
        name: "English Proficiency",
        isActive: true,
        qCount: 6714,
      },
      {
        id: 139,
        platformId: 14,
        name: "French",
        isActive: true,
        qCount: 6716,
      },
      {
        id: 140,
        platformId: 14,
        name: "Spanish",
        isActive: true,
        qCount: 7092,
      },
      {
        id: 141,
        platformId: 14,
        name: "German",
        isActive: true,
        qCount: 6841,
      },
      {
        id: 550,
        platformId: 45,
        name: "World Politics",
        isActive: true,
        qCount: 7538,
      },
      {
        id: 551,
        platformId: 45,
        name: "Indian Political System",
        isActive: true,
        qCount: 7545,
      },
      {
        id: 552,
        platformId: 45,
        name: "Civic Awareness",
        isActive: true,
        qCount: 7069,
      },
      {
        id: 144,
        platformId: 24,
        name: "History",
        isActive: true,
        qCount: 3095,
      },
      {
        id: 149,
        platformId: 24,
        name: "Art & Literature",
        isActive: true,
        qCount: 3469,
      },
      {
        id: 150,
        platformId: 24,
        name: "Technology",
        isActive: true,
        qCount: 3674,
      },
      {
        id: 151,
        platformId: 24,
        name: "Economy",
        isActive: true,
        qCount: 3503,
      },
      {
        id: 152,
        platformId: 24,
        name: "Culture",
        isActive: true,
        qCount: 4148,
      },
      {
        id: 153,
        platformId: 24,
        name: "Current Affairs",
        isActive: true,
        qCount: 3662,
      },
      {
        id: 185,
        platformId: 32,
        name: "Literature",
        isActive: true,
        qCount: 7514,
      },
      {
        id: 186,
        platformId: 32,
        name: "History of Art",
        isActive: true,
        qCount: 8122,
      },
      {
        id: 187,
        platformId: 32,
        name: "Philosophy",
        isActive: true,
        qCount: 6931,
      },
      {
        id: 188,
        platformId: 32,
        name: "Music",
        isActive: true,
        qCount: 7582,
      },
      {
        id: 189,
        platformId: 32,
        name: "Visual Arts",
        isActive: true,
        qCount: 7262,
      },
      {
        id: 190,
        platformId: 32,
        name: "Performing Arts",
        isActive: true,
        qCount: 9215,
      },
      {
        id: 191,
        platformId: 32,
        name: "Linguistics",
        isActive: true,
        qCount: 7360,
      },
      {
        id: 192,
        platformId: 32,
        name: "Cultural Studies",
        isActive: true,
        qCount: 6242,
      },
      {
        id: 193,
        platformId: 32,
        name: "World History",
        isActive: true,
        qCount: 7561,
      },
      {
        id: 194,
        platformId: 32,
        name: "Religion & Mythology",
        isActive: true,
        qCount: 9059,
      },
      {
        id: 195,
        platformId: 33,
        name: "Travel Destinations",
        isActive: true,
        qCount: 4332,
      },
      {
        id: 204,
        platformId: 34,
        name: "Cognitive Psychology",
        isActive: true,
        qCount: 4186,
      },
      {
        id: 205,
        platformId: 35,
        name: "Basic Mechanics",
        isActive: true,
        qCount: 4528,
      },
      {
        id: 45,
        platformId: 4,
        name: "Corporate Finance and Accounting",
        isActive: true,
        qCount: 5436,
      },
      {
        id: 47,
        platformId: 4,
        name: "Personal Finance",
        isActive: true,
        qCount: 3791,
      },
      {
        id: 58,
        platformId: 8,
        name: "Statistics",
        isActive: true,
        qCount: 3670,
      },
      {
        id: 59,
        platformId: 10,
        name: "Ancient History",
        isActive: true,
        qCount: 6605,
      },
      {
        id: 60,
        platformId: 10,
        name: "Medieval History",
        isActive: true,
        qCount: 6526,
      },
      {
        id: 61,
        platformId: 10,
        name: "Modern History",
        isActive: true,
        qCount: 7578,
      },
      {
        id: 62,
        platformId: 11,
        name: "Physical Geography",
        isActive: true,
        qCount: 8793,
      },
      {
        id: 63,
        platformId: 11,
        name: "Human Geography",
        isActive: true,
        qCount: 7196,
      },
      {
        id: 64,
        platformId: 11,
        name: "Environmental Geography",
        isActive: true,
        qCount: 7657,
      },
      {
        id: 207,
        platformId: 35,
        name: "Industrial Machinery",
        isActive: true,
        qCount: 4393,
      },
      {
        id: 208,
        platformId: 35,
        name: "Engineering Drawing",
        isActive: true,
        qCount: 3853,
      },
      {
        id: 209,
        platformId: 35,
        name: "Maintenance & Repair",
        isActive: true,
        qCount: 3673,
      },
      {
        id: 210,
        platformId: 36,
        name: "World Mythologies",
        isActive: true,
        qCount: 5469,
      },
      {
        id: 211,
        platformId: 36,
        name: "Cultural Anthropology",
        isActive: true,
        qCount: 4407,
      },
      {
        id: 212,
        platformId: 36,
        name: "Folklore and Legends",
        isActive: true,
        qCount: 4456,
      },
      {
        id: 213,
        platformId: 36,
        name: "World Religions",
        isActive: true,
        qCount: 4220,
      },
      {
        id: 214,
        platformId: 36,
        name: "Festivals and Traditions",
        isActive: true,
        qCount: 3780,
      },
      {
        id: 183,
        platformId: 31,
        name: "Pollution & Waste Management",
        isActive: true,
        qCount: 3657,
      },
      {
        id: 534,
        platformId: 41,
        name: "Development Economics",
        isActive: true,
        qCount: 5265,
      },
      {
        id: 539,
        platformId: 43,
        name: "Human Nutrition",
        isActive: true,
        qCount: 6624,
      },
      {
        id: 540,
        platformId: 43,
        name: "Fitness and Exercise",
        isActive: true,
        qCount: 4866,
      },
      {
        id: 541,
        platformId: 43,
        name: "Preventive Healthcare",
        isActive: true,
        qCount: 4764,
      },
      {
        id: 542,
        platformId: 43,
        name: "Mental Health Awareness",
        isActive: true,
        qCount: 4350,
      },
      {
        id: 547,
        platformId: 1,
        name: "Nursing",
        isActive: true,
        qCount: 11109,
      },
      {
        id: 548,
        platformId: 45,
        name: "Constitutional Studies",
        isActive: true,
        qCount: 6889,
      },
      {
        id: 88,
        platformId: 17,
        name: "Brand Management",
        isActive: true,
        qCount: 5281,
      },
      {
        id: 89,
        platformId: 18,
        name: "Classical Mechanics",
        isActive: true,
        qCount: 5850,
      },
      {
        id: 90,
        platformId: 18,
        name: "Quantum Physics",
        isActive: true,
        qCount: 3730,
      },
      {
        id: 91,
        platformId: 18,
        name: "Thermodynamics",
        isActive: true,
        qCount: 1693,
      },
      {
        id: 92,
        platformId: 18,
        name: "Electromagnetism",
        isActive: true,
        qCount: 3455,
      },
      {
        id: 93,
        platformId: 18,
        name: "Optics",
        isActive: true,
        qCount: 4216,
      },
      {
        id: 94,
        platformId: 18,
        name: "Nuclear Physics",
        isActive: true,
        qCount: 3302,
      },
      {
        id: 95,
        platformId: 19,
        name: "Organic Chemistry",
        isActive: true,
        qCount: 5581,
      },
      {
        id: 96,
        platformId: 19,
        name: "Inorganic Chemistry",
        isActive: true,
        qCount: 4246,
      },
      {
        id: 97,
        platformId: 19,
        name: "Physical Chemistry",
        isActive: true,
        qCount: 3935,
      },
      {
        id: 98,
        platformId: 19,
        name: "Analytical Chemistry",
        isActive: true,
        qCount: 4352,
      },
      {
        id: 99,
        platformId: 19,
        name: "Biochemistry",
        isActive: true,
        qCount: 3376,
      },
      {
        id: 100,
        platformId: 20,
        name: "Botany",
        isActive: true,
        qCount: 5993,
      },
      {
        id: 101,
        platformId: 20,
        name: "Zoology",
        isActive: true,
        qCount: 4990,
      },
      {
        id: 102,
        platformId: 20,
        name: "Microbiology",
        isActive: true,
        qCount: 3906,
      },
      {
        id: 103,
        platformId: 20,
        name: "Genetics",
        isActive: true,
        qCount: 3628,
      },
      {
        id: 104,
        platformId: 20,
        name: "Biotechnology",
        isActive: true,
        qCount: 3364,
      },
      {
        id: 105,
        platformId: 9,
        name: "Banking Basics",
        isActive: true,
        qCount: 4222,
      },
      {
        id: 106,
        platformId: 9,
        name: "Financial Instruments",
        isActive: true,
        qCount: 4752,
      },
      {
        id: 107,
        platformId: 9,
        name: "Banking Operations",
        isActive: true,
        qCount: 3525,
      },
      {
        id: 108,
        platformId: 9,
        name: "Risk Management in Banking",
        isActive: true,
        qCount: 3352,
      },
      {
        id: 109,
        platformId: 9,
        name: "Banking Regulations",
        isActive: true,
        qCount: 4967,
      },
      {
        id: 549,
        platformId: 45,
        name: "Public Administration",
        isActive: true,
        qCount: 7774,
      },
      {
        id: 8,
        platformId: 12,
        name: "Software Engineering",
        isActive: true,
        qCount: 6718,
      },
      {
        id: 2,
        platformId: 12,
        name: "Mobile Development",
        isActive: true,
        qCount: 9140,
      },
      {
        id: 9,
        platformId: 12,
        name: "Game Development",
        isActive: true,
        qCount: 9967,
      },
      {
        id: 215,
        platformId: 37,
        name: "Teaching Methodologies",
        isActive: true,
        qCount: 3954,
      },
      {
        id: 216,
        platformId: 37,
        name: "Curriculum Development",
        isActive: true,
        qCount: 3913,
      },
      {
        id: 217,
        platformId: 37,
        name: "Educational Psychology",
        isActive: true,
        qCount: 4263,
      },
      {
        id: 218,
        platformId: 37,
        name: "Instructional Technology",
        isActive: true,
        qCount: 4544,
      },
      {
        id: 219,
        platformId: 37,
        name: "Assessment & Evaluation",
        isActive: true,
        qCount: 4196,
      },
      {
        id: 220,
        platformId: 38,
        name: "Computer Networks Basics",
        isActive: true,
        qCount: 5261,
      },
      {
        id: 221,
        platformId: 38,
        name: "IP Addressing and Subnetting",
        isActive: true,
        qCount: 3398,
      },
      {
        id: 222,
        platformId: 38,
        name: "Protocols and Ports",
        isActive: true,
        qCount: 4881,
      },
      {
        id: 223,
        platformId: 38,
        name: "Network Security",
        isActive: true,
        qCount: 4702,
      },
      {
        id: 224,
        platformId: 38,
        name: "Wireless and Mobile Networks",
        isActive: true,
        qCount: 4510,
      },
      {
        id: 643,
        platformId: 53,
        name: "Tamil Nadu State Board",
        isActive: true,
        qCount: 10024,
      },
      {
        id: 644,
        platformId: 53,
        name: "Karnataka SSLC & PUC",
        isActive: true,
        qCount: 8042,
      },
      {
        id: 645,
        platformId: 53,
        name: "Kerala Board of Public Examinations",
        isActive: true,
        qCount: 9377,
      },
      {
        id: 646,
        platformId: 53,
        name: "Maharashtra State Board (MSBSHSE)",
        isActive: true,
        qCount: 10604,
      },
      {
        id: 647,
        platformId: 53,
        name: "CBSE",
        isActive: true,
        qCount: 10808,
      },
      {
        id: 648,
        platformId: 53,
        name: "Andhra Pradesh / Telangana (BIE/APSCHE)",
        isActive: true,
        qCount: 10519,
      },
      {
        id: 20,
        platformId: 16,
        name: "Database Management",
        isActive: true,
        qCount: 4072,
      },
      {
        id: 21,
        platformId: 16,
        name: "IT Service Management",
        isActive: true,
        qCount: 3234,
      },
      {
        id: 22,
        platformId: 16,
        name: "DevOps & Automation",
        isActive: true,
        qCount: 3925,
      },
      {
        id: 23,
        platformId: 6,
        name: "Civil Services",
        isActive: true,
        qCount: 4388,
      },
      {
        id: 25,
        platformId: 6,
        name: "Railway Exams",
        isActive: true,
        qCount: 3428,
      },
      {
        id: 26,
        platformId: 6,
        name: "SSC Exams",
        isActive: true,
        qCount: 3935,
      },
      {
        id: 10,
        platformId: 12,
        name: "Machine Learning",
        isActive: true,
        qCount: 7550,
      },
      {
        id: 142,
        platformId: 12,
        name: "Artificial Intelligence",
        isActive: true,
        qCount: 19257,
      },
      {
        id: 155,
        platformId: 12,
        name: "Programming Languages",
        isActive: true,
        qCount: 52798,
      },
      {
        id: 156,
        platformId: 29,
        name: "Manual Testing",
        isActive: true,
        qCount: 3485,
      },
      {
        id: 157,
        platformId: 29,
        name: "Automation Testing",
        isActive: true,
        qCount: 4662,
      },
      {
        id: 158,
        platformId: 29,
        name: "Performance Testing",
        isActive: true,
        qCount: 3566,
      },
      {
        id: 159,
        platformId: 29,
        name: "API Testing",
        isActive: true,
        qCount: 3320,
      },
      {
        id: 160,
        platformId: 29,
        name: "Security Testing",
        isActive: true,
        qCount: 2988,
      },
      {
        id: 161,
        platformId: 29,
        name: "Mobile Testing",
        isActive: true,
        qCount: 4376,
      },
      {
        id: 162,
        platformId: 29,
        name: "Database Testing",
        isActive: true,
        qCount: 3504,
      },
      {
        id: 163,
        platformId: 29,
        name: "DevOps for Testers",
        isActive: true,
        qCount: 3329,
      },
      {
        id: 164,
        platformId: 29,
        name: "Agile Testing",
        isActive: true,
        qCount: 3491,
      },
      {
        id: 165,
        platformId: 29,
        name: "Testing Tools and Technologies",
        isActive: true,
        qCount: 4810,
      },
      {
        id: 166,
        platformId: 30,
        name: "Movies & TV Shows",
        isActive: true,
        qCount: 3129,
      },
      {
        id: 167,
        platformId: 30,
        name: "Music",
        isActive: true,
        qCount: 3450,
      },
      {
        id: 168,
        platformId: 30,
        name: "Sports",
        isActive: true,
        qCount: 3002,
      },
      {
        id: 169,
        platformId: 30,
        name: "Video Games",
        isActive: true,
        qCount: 3496,
      },
      {
        id: 170,
        platformId: 30,
        name: "Celebrities & Pop Culture",
        isActive: true,
        qCount: 2679,
      },
      {
        id: 171,
        platformId: 30,
        name: "Cartoons & Animation",
        isActive: true,
        qCount: 2761,
      },
      {
        id: 172,
        platformId: 30,
        name: "Streaming Platforms",
        isActive: true,
        qCount: 2812,
      },
      {
        id: 173,
        platformId: 30,
        name: "Comics & Superheroes",
        isActive: true,
        qCount: 2585,
      },
      {
        id: 174,
        platformId: 30,
        name: "Award Shows & Ceremonies",
        isActive: true,
        qCount: 2200,
      },
      {
        id: 175,
        platformId: 30,
        name: "World Records & Fun Facts",
        isActive: true,
        qCount: 1973,
      },
      {
        id: 176,
        platformId: 31,
        name: "Environmental Studies",
        isActive: true,
        qCount: 2007,
      },
      {
        id: 177,
        platformId: 31,
        name: "Climate Change",
        isActive: true,
        qCount: 2781,
      },
      {
        id: 178,
        platformId: 31,
        name: "Sustainability",
        isActive: true,
        qCount: 2414,
      },
      {
        id: 179,
        platformId: 31,
        name: "Renewable Energy",
        isActive: true,
        qCount: 3249,
      },
      {
        id: 180,
        platformId: 31,
        name: "Ecology",
        isActive: true,
        qCount: 2917,
      },
      {
        id: 181,
        platformId: 31,
        name: "Environmental Policy",
        isActive: true,
        qCount: 3639,
      },
      {
        id: 182,
        platformId: 31,
        name: "Conservation Science",
        isActive: true,
        qCount: 2400,
      },
      {
        id: 184,
        platformId: 31,
        name: "Earth Science",
        isActive: true,
        qCount: 3608,
      },
      {
        id: 524,
        platformId: 39,
        name: "Moral Philosophy",
        isActive: true,
        qCount: 2965,
      },
      {
        id: 525,
        platformId: 39,
        name: "Philosophy of Mind",
        isActive: true,
        qCount: 2719,
      },
      {
        id: 526,
        platformId: 39,
        name: "Political Philosophy",
        isActive: true,
        qCount: 4624,
      },
      {
        id: 673,
        platformId: 46,
        name: "Mental Health",
        isActive: true,
        qCount: 5508,
      },
      {
        id: 674,
        platformId: 46,
        name: "Mindfulness & Meditation",
        isActive: true,
        qCount: 5960,
      },
      {
        id: 675,
        platformId: 46,
        name: "Stress Management",
        isActive: true,
        qCount: 5592,
      },
      {
        id: 676,
        platformId: 46,
        name: "Sleep Science & Hygiene",
        isActive: true,
        qCount: 5499,
      },
      {
        id: 677,
        platformId: 46,
        name: "Nutrition & Diet",
        isActive: true,
        qCount: 5675,
      },
      {
        id: 678,
        platformId: 46,
        name: "Fitness & Exercise Science",
        isActive: true,
        qCount: 6066,
      },
      {
        id: 679,
        platformId: 46,
        name: "Habit Building & Behavior Change",
        isActive: true,
        qCount: 5864,
      },
      {
        id: 680,
        platformId: 46,
        name: "Time Management & Productivity",
        isActive: true,
        qCount: 5282,
      },
      {
        id: 681,
        platformId: 46,
        name: "Emotional Intelligence",
        isActive: true,
        qCount: 5845,
      },
      {
        id: 682,
        platformId: 46,
        name: "Relationships & Communication",
        isActive: true,
        qCount: 5621,
      },
      {
        id: 683,
        platformId: 46,
        name: "Self-Care & Resilience",
        isActive: true,
        qCount: 6066,
      },
      {
        id: 684,
        platformId: 46,
        name: "Digital Wellbeing",
        isActive: true,
        qCount: 5366,
      },
      {
        id: 685,
        platformId: 46,
        name: "Work–Life Balance & Burnout",
        isActive: true,
        qCount: 6024,
      },
      {
        id: 686,
        platformId: 46,
        name: "Positive Psychology",
        isActive: true,
        qCount: 6035,
      },
      {
        id: 687,
        platformId: 46,
        name: "Yoga & Breathwork",
        isActive: true,
        qCount: 6651,
      },
      {
        id: 688,
        platformId: 46,
        name: "Longevity & Healthy Aging",
        isActive: true,
        qCount: 5652,
      },
      {
        id: 689,
        platformId: 46,
        name: "Women's Health",
        isActive: true,
        qCount: 6093,
      },
      {
        id: 690,
        platformId: 46,
        name: "Men's Health",
        isActive: true,
        qCount: 6499,
      },
      {
        id: 691,
        platformId: 46,
        name: "Substance Use & Recovery",
        isActive: true,
        qCount: 5849,
      }
  ]);

  const [subjectRows, platformRows] = await Promise.all([
    db.select({ id: Subject.id, platformId: Subject.platformId }).from(Subject),
    db.select({ id: Platform.id }).from(Platform),
  ]);

  const subjectPlatformMap = new Map<number, number>();
  for (const row of subjectRows) {
    subjectPlatformMap.set(row.id, row.platformId);
  }

  const platformIds = new Set(platformRows.map((row) => row.id));

  const topics = (topicsData as TopicJson[])
    .filter((item): item is TopicJson => typeof item?.id === 'number')
    .filter((item) => {
      if (!platformIds.has(item.platform_id)) {
        return false;
      }
      const subjectPlatformId = subjectPlatformMap.get(item.subject_id);
      return typeof subjectPlatformId === 'number' && subjectPlatformId === item.platform_id;
    })
    .map((item) => ({
      id: item.id,
      platformId: item.platform_id,
      subjectId: item.subject_id,
      name: item.name,
      isActive: item.is_active,
      qCount: item.q_count ?? 0,
    }));

  let insertedTopicsCount = 0;
  if (topics.length > 0) {
    console.log(`Seeding ${topics.length} topics (after validation)`);
    const batchSize = 100;
    for (let i = 0; i < topics.length; i += batchSize) {
      const batch = topics.slice(i, i + batchSize);
      try {
        await db.insert(Topic).values(batch);
        insertedTopicsCount += batch.length;
      } catch (err) {
        for (const entry of batch) {
          try {
            await db.insert(Topic).values(entry);
            insertedTopicsCount += 1;
          } catch (singleErr) {
            console.error('Skipping topic during seed', entry.id, singleErr instanceof Error ? singleErr.message : singleErr);
          }
        }
      }
    }
  }

  if (insertedTopicsCount > 0) {
    console.log(`Inserted ${insertedTopicsCount} topics`);
  }

  const topicRows = await db.select({ id: Topic.id, platformId: Topic.platformId, subjectId: Topic.subjectId }).from(Topic);
  const topicLookup = new Map<number, { platformId: number; subjectId: number }>();
  for (const row of topicRows) {
    topicLookup.set(row.id, { platformId: row.platformId, subjectId: row.subjectId });
  }

  const roadmaps = (roadmapsData as RoadmapJson[])
    .filter((item): item is RoadmapJson => typeof item?.id === 'number')
    .filter((item) => {
      if (!platformIds.has(item.platform_id)) {
        return false;
      }
      const subjectPlatformId = subjectPlatformMap.get(item.subject_id);
      if (typeof subjectPlatformId !== 'number' || subjectPlatformId !== item.platform_id) {
        return false;
      }
      const topicEntry = topicLookup.get(item.topic_id);
      if (!topicEntry) {
        return false;
      }
      return topicEntry.platformId === item.platform_id && topicEntry.subjectId === item.subject_id;
    })
    .map((item) => ({
      id: item.id,
      platformId: item.platform_id,
      subjectId: item.subject_id,
      topicId: item.topic_id,
      name: item.name,
      isActive: item.is_active,
      qCount: item.q_count ?? 0,
    }));

  if (roadmaps.length > 0) {
    console.log(`Seeding ${roadmaps.length} roadmaps (after validation)`);
    const batchSize = 100;
    let insertedRoadmapsCount = 0;
    for (let i = 0; i < roadmaps.length; i += batchSize) {
      const batch = roadmaps.slice(i, i + batchSize);
      try {
        await db.insert(Roadmap).values(batch);
        insertedRoadmapsCount += batch.length;
      } catch (err) {
        for (const entry of batch) {
          try {
            await db.insert(Roadmap).values(entry);
            insertedRoadmapsCount += 1;
          } catch (singleErr) {
            console.error('Skipping roadmap during seed', entry.id, singleErr instanceof Error ? singleErr.message : singleErr);
          }
        }
      }
    }
    console.log(`Inserted ${insertedRoadmapsCount} roadmaps`);
  }
}
