import {
  aiPlaybooks,
  createLessonModuleRecord,
  createLessonWorkspaceItem,
} from './schema';
import type {
  LessonAiPlaybook,
  LessonInsight,
  LessonModuleRecord,
  LessonTimelineEvent,
  LessonWorkspaceItem,
} from '../../types/lesson';

const withDate = (value: string) => new Date(value).toISOString();

export const getSampleLessons = (): LessonWorkspaceItem[] => {
  const energyLab = createLessonWorkspaceItem({
    id: 'lesson-energy-lab',
    title: 'Renewable Energy Lab',
    slug: 'renewable-energy-lab',
    subject: 'Science',
    gradeBand: 'Grades 7-8',
    status: 'published',
    templateKey: 'stem-lab',
    duration: 55,
    tags: ['science', 'energy', 'lab'],
    plan: 'pro',
    createdAt: withDate('2024-01-22T09:00:00Z'),
    updatedAt: withDate('2024-03-12T13:40:00Z'),
    moduleId: 'module-sustainable-tech',
    aiUsage: {
      outline: true,
      objectives: true,
      activities: true,
      materials: true,
      quiz: true,
      translation: false,
      tokensUsed: 14500,
      lastRunAt: withDate('2024-03-12T13:40:00Z'),
    },
    objectives: [
      {
        id: crypto.randomUUID(),
        statement: 'Differentiate renewable and non-renewable energy sources.',
        successCriteria: 'Learners classify 10 energy cards with 90% accuracy and provide one justification.',
        bloomsLevel: 'analyse',
      },
      {
        id: crypto.randomUUID(),
        statement: 'Design a testable hypothesis for a small-scale wind turbine.',
        successCriteria: 'Groups articulate variables, predict outcomes, and list required materials.',
        bloomsLevel: 'create',
      },
    ],
    blocks: [
      {
        id: crypto.randomUUID(),
        type: 'warmup',
        title: 'Energy quick write',
        minutes: 8,
        objectiveId: null,
        instructions: 'Students respond to the prompt “What powers our city?” with three bullet predictions.',
        resources: ['Prompt slide'],
        aiSuggested: true,
      },
      {
        id: crypto.randomUUID(),
        type: 'teach',
        title: 'Concept mini-lesson',
        minutes: 12,
        objectiveId: null,
        instructions: 'Teacher facilitates a short demo comparing fossil fuel and renewable outputs with visuals.',
        resources: ['Concept slides', 'Live data feed'],
        aiSuggested: false,
      },
      {
        id: crypto.randomUUID(),
        type: 'explore',
        title: 'Turbine build rotation',
        minutes: 20,
        objectiveId: null,
        instructions: 'Teams assemble desktop turbines, capture rotations per minute, and document findings.',
        resources: ['Lab worksheet', 'Turbine kit checklist'],
        aiSuggested: true,
      },
      {
        id: crypto.randomUUID(),
        type: 'assess',
        title: 'Exit ticket',
        minutes: 10,
        objectiveId: null,
        instructions: 'Learners answer two open questions on energy trade-offs and upload to LMS.',
        resources: ['Exit ticket form'],
        aiSuggested: false,
      },
      {
        id: crypto.randomUUID(),
        type: 'wrapup',
        title: 'Reflection circle',
        minutes: 5,
        objectiveId: null,
        instructions: 'Pair-share key discoveries and set a goal for the next build iteration.',
        resources: [],
        aiSuggested: false,
      },
    ],
    resources: [
      {
        id: crypto.randomUUID(),
        type: 'slide',
        label: 'Energy mix slides',
        url: 'https://cdn.ansiversa.com/lesson/energy-mix-slides',
        notes: 'AI generated infographics with region-specific data.',
        plan: 'pro',
      },
      {
        id: crypto.randomUUID(),
        type: 'worksheet',
        label: 'Lab data capture sheet',
        url: 'https://cdn.ansiversa.com/lesson/energy-lab-sheet',
        notes: 'Auto-calculates averages and trends.',
        plan: 'free',
      },
    ],
    accommodations: [
      {
        id: crypto.randomUUID(),
        type: 'support',
        audience: 'ELL',
        description: 'Provide dual-language vocabulary cards with icons.',
      },
      {
        id: crypto.randomUUID(),
        type: 'extension',
        audience: 'Advanced learners',
        description: 'Challenge groups to model energy savings for a smart campus.',
      },
    ],
    schedule: {
      targetDate: '2024-03-15',
      pacing: 'single',
      totalMinutes: 55,
      calendarExported: true,
    },
    quiz: {
      quizId: 'quiz-energy-basics',
      title: 'Energy Exit Ticket',
      status: 'linked',
      questionCount: 6,
      lastSyncedAt: withDate('2024-03-12T13:45:00Z'),
    },
    analytics: {
      exports: 5,
      aiRuns: 4,
      learnersImpacted: 96,
      notes: 'Published to Sustainable Tech Sprint module and shared with two partner schools.',
    },
    timelineStatus: 'completed',
  });

  const narrativeWriting = createLessonWorkspaceItem({
    id: 'lesson-narrative-writing',
    title: 'Storytelling with Sensory Details',
    slug: 'storytelling-with-sensory-details',
    subject: 'Language Arts',
    gradeBand: 'Grades 5-6',
    status: 'draft',
    templateKey: 'language-arts',
    duration: 45,
    tags: ['writing workshop', 'mentor text'],
    plan: 'free',
    createdAt: withDate('2024-02-10T09:00:00Z'),
    updatedAt: withDate('2024-03-08T09:20:00Z'),
    moduleId: 'module-digital-storytelling',
    aiUsage: {
      outline: true,
      objectives: true,
      activities: false,
      materials: false,
      quiz: false,
      translation: false,
      tokensUsed: 6200,
      lastRunAt: withDate('2024-03-08T09:15:00Z'),
    },
    objectives: [
      {
        id: crypto.randomUUID(),
        statement: 'Use vivid sensory language to show rather than tell in a narrative paragraph.',
        successCriteria: 'Student drafts include three senses and at least one figurative language example.',
        bloomsLevel: 'create',
      },
    ],
    blocks: [
      {
        id: crypto.randomUUID(),
        type: 'warmup',
        title: 'Descriptive writing sprint',
        minutes: 7,
        objectiveId: null,
        instructions: 'Learners free-write about the cafeteria using as many senses as possible.',
        resources: ['Prompt card'],
        aiSuggested: true,
      },
      {
        id: crypto.randomUUID(),
        type: 'teach',
        title: 'Mentor text close read',
        minutes: 10,
        objectiveId: null,
        instructions: 'Annotate a mentor paragraph highlighting sensory verbs and figurative language.',
        resources: ['Mentor text PDF'],
        aiSuggested: false,
      },
      {
        id: crypto.randomUUID(),
        type: 'practice',
        title: 'Partner revision',
        minutes: 15,
        objectiveId: null,
        instructions: 'Pairs exchange drafts, offer glow/grow feedback, and revise in real time.',
        resources: ['Feedback checklist'],
        aiSuggested: false,
      },
      {
        id: crypto.randomUUID(),
        type: 'wrapup',
        title: 'Author share',
        minutes: 8,
        objectiveId: null,
        instructions: 'Two volunteers read revisions and class names standout sensory choices.',
        resources: [],
        aiSuggested: false,
      },
    ],
    resources: [
      {
        id: crypto.randomUUID(),
        type: 'worksheet',
        label: 'Sensory detail checklist',
        url: 'https://cdn.ansiversa.com/lesson/sensory-checklist',
        notes: 'Printed and digital versions included.',
        plan: 'free',
      },
    ],
    accommodations: [
      {
        id: crypto.randomUUID(),
        type: 'support',
        audience: 'Learners with writing accommodations',
        description: 'Offer speech-to-text and pre-highlighted mentor text examples.',
      },
      {
        id: crypto.randomUUID(),
        type: 'extension',
        audience: 'Advanced writers',
        description: 'Challenge to incorporate mood via setting and pacing adjustments.',
      },
    ],
    schedule: {
      targetDate: '2024-03-22',
      pacing: 'single',
      totalMinutes: 45,
      calendarExported: false,
    },
    quiz: {
      quizId: null,
      title: null,
      status: 'not-linked',
      questionCount: 0,
      lastSyncedAt: null,
    },
    analytics: {
      exports: 1,
      aiRuns: 2,
      learnersImpacted: 64,
      notes: 'Awaiting mentor text approvals before publishing.',
    },
    timelineStatus: 'on-track',
  });

  const pythonLoops = createLessonWorkspaceItem({
    id: 'lesson-python-loops',
    title: 'Python Loops for Robotics Sensors',
    slug: 'python-loops-for-robotics',
    subject: 'Computer Science',
    gradeBand: 'Grades 9-10',
    status: 'scheduled',
    templateKey: 'coding-workshop',
    duration: 60,
    tags: ['python', 'robotics'],
    plan: 'pro',
    createdAt: withDate('2024-01-30T11:00:00Z'),
    updatedAt: withDate('2024-03-10T16:30:00Z'),
    moduleId: 'module-sustainable-tech',
    aiUsage: {
      outline: true,
      objectives: true,
      activities: true,
      materials: true,
      quiz: false,
      translation: true,
      tokensUsed: 9800,
      lastRunAt: withDate('2024-03-10T16:00:00Z'),
    },
    objectives: [
      {
        id: crypto.randomUUID(),
        statement: 'Write for-loops that process sensor arrays for anomaly detection.',
        successCriteria: 'Given sensor data, learners output formatted alerts with thresholds applied.',
        bloomsLevel: 'apply',
      },
    ],
    blocks: [
      {
        id: crypto.randomUUID(),
        type: 'warmup',
        title: 'Debug challenge',
        minutes: 10,
        objectiveId: null,
        instructions: 'Students fix a loop that overflows sensor readings.',
        resources: ['Debug snippet'],
        aiSuggested: true,
      },
      {
        id: crypto.randomUUID(),
        type: 'teach',
        title: 'Mini-lesson: loops and lists',
        minutes: 15,
        objectiveId: null,
        instructions: 'Instructor demonstrates iteration patterns with live coding.',
        resources: ['Live coding notebook'],
        aiSuggested: false,
      },
      {
        id: crypto.randomUUID(),
        type: 'practice',
        title: 'Pair programming sprint',
        minutes: 25,
        objectiveId: null,
        instructions: 'Pairs write loops to smooth sensor data and send to dashboard.',
        resources: ['Sensor dataset', 'API docs'],
        aiSuggested: true,
      },
      {
        id: crypto.randomUUID(),
        type: 'wrapup',
        title: 'Retro and next steps',
        minutes: 10,
        objectiveId: null,
        instructions: 'Teams share insights via 1-2-4-all and log backlog tasks.',
        resources: [],
        aiSuggested: false,
      },
    ],
    resources: [
      {
        id: crypto.randomUUID(),
        type: 'document',
        label: 'Robotics sensor starter code',
        url: 'https://cdn.ansiversa.com/lesson/robotics-loop-starter',
        notes: 'Includes inline comments for scaffolding.',
        plan: 'pro',
      },
    ],
    accommodations: [
      {
        id: crypto.randomUUID(),
        type: 'support',
        audience: 'Learners needing pacing supports',
        description: 'Provide partially completed notebooks and checkpoints.',
      },
      {
        id: crypto.randomUUID(),
        type: 'accessibility',
        audience: 'Color-blind learners',
        description: 'Use accessible palette in dashboards and highlight text cues.',
      },
    ],
    schedule: {
      targetDate: '2024-03-28',
      pacing: 'double',
      totalMinutes: 120,
      calendarExported: false,
    },
    quiz: {
      quizId: null,
      title: null,
      status: 'generated',
      questionCount: 8,
      lastSyncedAt: withDate('2024-03-10T16:05:00Z'),
    },
    analytics: {
      exports: 2,
      aiRuns: 5,
      learnersImpacted: 72,
      notes: 'Scheduled for robotics showcase; translation enabled for Arabic.',
    },
    timelineStatus: 'attention',
  });

  const pitchStudio = createLessonWorkspaceItem({
    id: 'lesson-pitch-studio',
    title: 'Entrepreneurship Pitch Studio',
    slug: 'entrepreneurship-pitch-studio',
    subject: 'Business and Entrepreneurship',
    gradeBand: 'Higher Ed / Corporate',
    status: 'draft',
    templateKey: 'business-strategy',
    duration: 70,
    tags: ['pitch', 'presentation'],
    plan: 'pro',
    createdAt: withDate('2024-02-05T14:00:00Z'),
    updatedAt: withDate('2024-03-09T11:20:00Z'),
    moduleId: 'module-sustainable-tech',
    aiUsage: {
      outline: true,
      objectives: true,
      activities: true,
      materials: false,
      quiz: false,
      translation: true,
      tokensUsed: 7800,
      lastRunAt: withDate('2024-03-09T11:00:00Z'),
    },
    objectives: [
      {
        id: crypto.randomUUID(),
        statement: 'Deliver a persuasive two-minute pitch highlighting customer problem, solution, and traction.',
        successCriteria: 'Pitch hits 4/5 rubric indicators and responds to Q and A with evidence.',
        bloomsLevel: 'evaluate',
      },
    ],
    blocks: [
      {
        id: crypto.randomUUID(),
        type: 'warmup',
        title: 'Hook remix circle',
        minutes: 10,
        objectiveId: null,
        instructions: 'Teams rewrite classic hooks for sustainability ventures.',
        resources: ['Hook examples'],
        aiSuggested: true,
      },
      {
        id: crypto.randomUUID(),
        type: 'teach',
        title: 'Investor pitch teardown',
        minutes: 12,
        objectiveId: null,
        instructions: 'Analyse clips from winning pitches and annotate the rubric.',
        resources: ['Pitch video playlist'],
        aiSuggested: false,
      },
      {
        id: crypto.randomUUID(),
        type: 'practice',
        title: 'Peer pitch lab',
        minutes: 30,
        objectiveId: null,
        instructions: 'Teams deliver drafts, capture feedback notes, and iterate in breakout rooms.',
        resources: ['Feedback rubric', 'Timer'],
        aiSuggested: true,
      },
      {
        id: crypto.randomUUID(),
        type: 'assess',
        title: 'Pitch recording and reflection',
        minutes: 18,
        objectiveId: null,
        instructions: 'Record a one-take pitch and complete self-assessment reflection.',
        resources: ['Recording booth checklist'],
        aiSuggested: false,
      },
    ],
    resources: [
      {
        id: crypto.randomUUID(),
        type: 'slide',
        label: 'Pitch deck template',
        url: 'https://cdn.ansiversa.com/lesson/pitch-deck-template',
        notes: 'Includes AI-generated icon library.',
        plan: 'pro',
      },
      {
        id: crypto.randomUUID(),
        type: 'document',
        label: 'Investor Q and A prompts',
        url: 'https://cdn.ansiversa.com/lesson/pitch-qa-prompts',
        notes: 'Used for mock panel practice.',
        plan: 'free',
      },
    ],
    accommodations: [
      {
        id: crypto.randomUUID(),
        type: 'support',
        audience: 'Learners with public speaking anxiety',
        description: 'Offer optional audio-only submissions and gradual exposure coaching.',
      },
      {
        id: crypto.randomUUID(),
        type: 'accessibility',
        audience: 'Deaf or hard of hearing participants',
        description: 'Provide captioned exemplars and interpreter notes in advance.',
      },
    ],
    schedule: {
      targetDate: '2024-04-05',
      pacing: 'flex',
      totalMinutes: 210,
      calendarExported: false,
    },
    quiz: {
      quizId: 'quiz-pitch-readiness',
      title: 'Pitch Readiness Checklist',
      status: 'generated',
      questionCount: 5,
      lastSyncedAt: withDate('2024-03-09T11:10:00Z'),
    },
    analytics: {
      exports: 0,
      aiRuns: 4,
      learnersImpacted: 48,
      notes: 'Add bilingual pitch rubrics before publishing to cohort.',
    },
    timelineStatus: 'on-track',
  });

  const empathyInterviews = createLessonWorkspaceItem({
    id: 'lesson-empathy-interviews',
    title: 'Empathy Interviews and Journey Mapping',
    slug: 'empathy-interviews-journey-mapping',
    subject: 'Soft Skills',
    gradeBand: 'Grades 9-12',
    status: 'published',
    templateKey: 'soft-skills',
    duration: 50,
    tags: ['design thinking', 'sel'],
    plan: 'free',
    createdAt: withDate('2024-01-18T08:30:00Z'),
    updatedAt: withDate('2024-03-05T08:30:00Z'),
    moduleId: 'module-digital-storytelling',
    aiUsage: {
      outline: true,
      objectives: true,
      activities: true,
      materials: false,
      quiz: false,
      translation: false,
      tokensUsed: 4300,
      lastRunAt: withDate('2024-03-05T08:00:00Z'),
    },
    objectives: [
      {
        id: crypto.randomUUID(),
        statement: 'Conduct empathy interviews that surface needs, emotions, and opportunities.',
        successCriteria: 'Teams document at least three insights mapped to a user journey stage.',
        bloomsLevel: 'analyse',
      },
    ],
    blocks: [
      {
        id: crypto.randomUUID(),
        type: 'warmup',
        title: 'Active listening circle',
        minutes: 6,
        objectiveId: null,
        instructions: 'Practice paraphrasing partner stories in trios.',
        resources: ['Listening stems'],
        aiSuggested: true,
      },
      {
        id: crypto.randomUUID(),
        type: 'teach',
        title: 'Interview protocol demo',
        minutes: 12,
        objectiveId: null,
        instructions: 'Model open vs. closed questioning and note-taking strategies.',
        resources: ['Protocol slides'],
        aiSuggested: false,
      },
      {
        id: crypto.randomUUID(),
        type: 'explore',
        title: 'Field interviews',
        minutes: 20,
        objectiveId: null,
        instructions: 'Teams interview stakeholders and capture quotes on shared mural board.',
        resources: ['Mural template'],
        aiSuggested: true,
      },
      {
        id: crypto.randomUUID(),
        type: 'wrapup',
        title: 'Journey map synthesis',
        minutes: 12,
        objectiveId: null,
        instructions: 'Translate interview notes into pain points, gains, and opportunities.',
        resources: ['Journey map canvas'],
        aiSuggested: false,
      },
    ],
    resources: [
      {
        id: crypto.randomUUID(),
        type: 'document',
        label: 'Interview note template',
        url: 'https://cdn.ansiversa.com/lesson/empathy-interview-template',
        notes: 'Pre-translated prompts for bilingual teams.',
        plan: 'free',
      },
    ],
    accommodations: [
      {
        id: crypto.randomUUID(),
        type: 'support',
        audience: 'Neurodivergent learners',
        description: 'Provide clear scripts and option to observe before leading interviews.',
      },
      {
        id: crypto.randomUUID(),
        type: 'extension',
        audience: 'Advanced teams',
        description: 'Synthesize quotes into opportunity statements for next sprint.',
      },
    ],
    schedule: {
      targetDate: '2024-03-14',
      pacing: 'single',
      totalMinutes: 50,
      calendarExported: true,
    },
    quiz: {
      quizId: 'quiz-empathy-check',
      title: 'Empathy Interview Reflection',
      status: 'linked',
      questionCount: 4,
      lastSyncedAt: withDate('2024-03-05T08:10:00Z'),
    },
    analytics: {
      exports: 3,
      aiRuns: 3,
      learnersImpacted: 88,
      notes: 'Shared widely across innovation academies with localisation support.',
    },
    timelineStatus: 'completed',
  });

  return [energyLab, narrativeWriting, pythonLoops, pitchStudio, empathyInterviews];
};

export const getSampleModules = (): LessonModuleRecord[] => {
  const sustainableTech = createLessonModuleRecord({
    id: 'module-sustainable-tech',
    title: 'Sustainable Tech Sprint',
    slug: 'sustainable-tech-sprint',
    subject: 'STEM and Entrepreneurship',
    gradeBand: 'Grades 9-10',
    status: 'draft',
    description:
      'Blend renewable energy science, coding, and venture storytelling into a week-long sprint culminating in investor pitches.',
    outcomes: [
      'Teams prototype and justify a sustainable energy solution for a local challenge.',
      'Learners translate technical insights into persuasive pitches with data-backed storytelling.',
    ],
    prerequisites: [
      'Baseline familiarity with Python syntax.',
      'Teams selected and project charters drafted.',
    ],
    plan: 'pro',
    createdAt: withDate('2024-02-01T10:00:00Z'),
    updatedAt: withDate('2024-03-12T14:00:00Z'),
    lessonIds: ['lesson-energy-lab', 'lesson-python-loops', 'lesson-pitch-studio'],
    sequence: [
      {
        lessonId: 'lesson-energy-lab',
        title: 'Renewable Energy Lab',
        duration: 55,
        status: 'published',
        day: 1,
        focus: 'Investigate energy sources and capture data.',
      },
      {
        lessonId: 'lesson-python-loops',
        title: 'Python Loops for Robotics Sensors',
        duration: 60,
        status: 'scheduled',
        day: 2,
        focus: 'Process energy data and automate dashboards.',
      },
      {
        lessonId: 'lesson-pitch-studio',
        title: 'Entrepreneurship Pitch Studio',
        duration: 70,
        status: 'draft',
        day: 3,
        focus: 'Craft persuasive venture pitches with investor feedback.',
      },
    ],
    pacing: {
      weeks: 1,
      hoursPerWeek: 6,
      totalMinutes: 185,
      calendarExported: false,
    },
    leadInstructor: 'Karthik — Lead Instructor',
    analytics: {
      publishedLessons: 1,
      drafts: 2,
      exports: 2,
      shareUrl: null,
    },
  });

  const digitalStorytelling = createLessonModuleRecord({
    id: 'module-digital-storytelling',
    title: 'Digital Storytelling Sprint',
    slug: 'digital-storytelling-sprint',
    subject: 'Language Arts and SEL',
    gradeBand: 'Grades 5-6',
    status: 'published',
    description:
      'Coach learners to gather empathy insights and transform them into vivid written narratives and multimedia stories.',
    outcomes: [
      'Writers craft mentor-text inspired narratives with sensory richness.',
      'Teams apply empathy interview findings to highlight authentic voices.',
    ],
    prerequisites: [
      'Secure interview permissions.',
      'Collect sample mentor texts and multimedia examples.',
    ],
    plan: 'free',
    createdAt: withDate('2024-01-15T08:00:00Z'),
    updatedAt: withDate('2024-03-08T09:20:00Z'),
    lessonIds: ['lesson-narrative-writing', 'lesson-empathy-interviews'],
    sequence: [
      {
        lessonId: 'lesson-empathy-interviews',
        title: 'Empathy Interviews and Journey Mapping',
        duration: 50,
        status: 'published',
        day: 1,
        focus: 'Surface authentic needs and opportunities through interviews.',
      },
      {
        lessonId: 'lesson-narrative-writing',
        title: 'Storytelling with Sensory Details',
        duration: 45,
        status: 'draft',
        day: 2,
        focus: 'Craft narratives that highlight empathy insights with vivid detail.',
      },
    ],
    pacing: {
      weeks: 2,
      hoursPerWeek: 2,
      totalMinutes: 95,
      calendarExported: true,
    },
    leadInstructor: 'Maria Chen — Literacy Coach',
    analytics: {
      publishedLessons: 1,
      drafts: 1,
      exports: 4,
      shareUrl: 'https://ansiversa.com/lesson/module/digital-storytelling-sprint',
    },
  });

  return [sustainableTech, digitalStorytelling];
};

export const getSampleTimelineEvents = (): LessonTimelineEvent[] => [
  {
    id: 'timeline-energy-export',
    lessonId: 'lesson-energy-lab',
    title: 'Exported PDF for partner school',
    targetDate: '2024-03-01',
    status: 'completed',
    notes: 'Shared annotated lab instructions with Dubai STEM Hub.',
  },
  {
    id: 'timeline-python-review',
    lessonId: 'lesson-python-loops',
    title: 'Review AI generated quiz questions',
    targetDate: '2024-03-18',
    status: 'attention',
    notes: 'Double-check coding distractors before publishing.',
  },
  {
    id: 'timeline-pitch-watermark',
    lessonId: 'lesson-pitch-studio',
    title: 'Remove watermark from pitch export',
    targetDate: '2024-03-25',
    status: 'attention',
    notes: 'Requires Pro upgrade to export without watermark.',
  },
  {
    id: 'timeline-narrative-publish',
    lessonId: 'lesson-narrative-writing',
    title: 'Publish narrative workshop',
    targetDate: '2024-03-22',
    status: 'on-track',
    notes: 'Awaiting principal approval for mentor text usage.',
  },
  {
    id: 'timeline-empathy-calendar',
    lessonId: 'lesson-empathy-interviews',
    title: 'Sync module calendar to Outlook',
    targetDate: '2024-03-12',
    status: 'completed',
    notes: 'Calendar export shared with grade-level teams.',
  },
];

export const getSampleInsights = (): LessonInsight[] => [
  {
    id: 'insight-plan-limit',
    message: 'Free plan limit: 1 lesson left before you reach the 10 lesson cap. Upgrade for unlimited drafts and watermark-free exports.',
    type: 'warning',
    icon: 'fas fa-triangle-exclamation',
    timestamp: 'Just now',
  },
  {
    id: 'insight-ai-usage',
    message: 'AI Outline was run 4 times this week. Boost accuracy by adding audience context before generating.',
    type: 'info',
    icon: 'fas fa-robot',
    timestamp: '2h ago',
  },
  {
    id: 'insight-quiz-link',
    message: 'Quiz Institute: Energy Exit Ticket has 2 new attempts. Sync to pull updated analytics.',
    type: 'success',
    icon: 'fas fa-link',
    timestamp: 'Yesterday',
  },
];

export const getSampleAiPlaybooks = (): LessonAiPlaybook[] => aiPlaybooks;
