import { db, Platform } from 'astro:db';

// https://astro.build/db/seed
export default async function seed() {
	await db.insert(Platform).values([
    { name: "Architecture & Urban Planning" },
    { name: "Arts & Humanities" },
    { name: "Astronomy & Space" },
    { name: "Banking" },
    { name: "Biology" },
    { name: "Business" },
    { name: "Chemistry" },
    { name: "Civics & Governance" },
    { name: "Culinary Arts" },
    { name: "Culture & Mythology" },
    { name: "Design & UX" },
    { name: "Driving" },
    { name: "Economics" },
    { name: "Education & Teaching" },
    { name: "Engineering" },
    { name: "Entertainment" },
    { name: "Environmental Science" },
    { name: "Ethical Hacking & Cybersecurity" },
    { name: "Ethics and Philosophy" },
    { name: "Finance" },
    { name: "Game Design & Theory" },
    { name: "General Knowledge" },
    { name: "Geography" },
    { name: "Government Exams" },
    { name: "Health & Nutrition" },
    { name: "Higher Education Prep" },
    { name: "History" },
    { name: "IT Certifications" },
    { name: "Languages & Literature" },
    { name: "Language Tests" },
    { name: "Law" },
    { name: "Logical Reasoning" },
    { name: "Marketing" },
    { name: "Mathematics" },
    { name: "Mechanical Skills" },
    { name: "Medical" },
    { name: "Networking" },
    { name: "Physics" },
    { name: "Programming" },
    { name: "Psychology" },
    { name: "Quantitative Aptitude" },
    { name: "School" },
    { name: "Soft Skills" },
    { name: "Testing" },
    { name: "Travel & Tourism" },
    { name: "Wellness & Lifestyle" },
  ]);
}
