import type { MemoryTrainerSampleData } from '../../types/memory-trainer';

const now = new Date();
const iso = (date: Date) => date.toISOString();

const daysAgo = (days: number): string => {
  const d = new Date(now);
  d.setUTCDate(d.getUTCDate() - days);
  return iso(d);
};

export const getSampleMemoryTrainerData = (): MemoryTrainerSampleData => ({
  plan: [
    {
      id: 'warmup-audio-flex',
      phase: 'warmup',
      title: 'Warm-up: Audio Flex',
      description: 'Quick dual-channel warm-up priming auditory and spatial buffers.',
      durationMinutes: 4,
      exercises: ['nback'],
      status: 'pending',
      targetAccuracy: 0.75,
      notes: 'Short sequence, focus on rhythm of tones.',
    },
    {
      id: 'focus-dual-nback',
      phase: 'focus',
      title: 'Focus: Dual N-back Burst',
      description: 'Three rounds of dual N-back with adaptive promotion logic enabled.',
      durationMinutes: 8,
      exercises: ['nback'],
      status: 'pending',
      targetAccuracy: 0.82,
      notes: 'Maintain latency below 650ms to unlock level 3.',
    },
    {
      id: 'focus-span-switch',
      phase: 'focus',
      title: 'Focus: Span Switch Drills',
      description: 'Alternating digit and letter spans with reverse recall challenge.',
      durationMinutes: 7,
      exercises: ['span'],
      status: 'pending',
      targetAccuracy: 0.78,
      notes: 'Reverse trials emphasise chunking strategy.',
    },
    {
      id: 'cooldown-srs',
      phase: 'cooldown',
      title: 'Cooldown: SRS Reflections',
      description: 'Review due flashcards and jot micro reflections for retention.',
      durationMinutes: 6,
      exercises: ['srs'],
      status: 'pending',
      targetAccuracy: 0.9,
      notes: 'Finish with 5 reflection prompts from FlashNote.',
    },
  ],
  planSummary: {
    totalMinutes: 25,
    focusMinutes: 15,
    cooldownMinutes: 6,
  },
  streak: {
    current: 9,
    best: 21,
    longestBreak: 3,
    lastCompleted: daysAgo(0),
  },
  reminder: {
    enabled: true,
    time: '07:30',
    timezone: 'UTC+05:30',
    days: ['Mon', 'Tue', 'Wed', 'Thu', 'Sat'],
  },
  exercises: [
    {
      type: 'nback',
      title: 'Adaptive Dual N-back',
      description: 'Tracks both grid and audio matches with Elo-style leveling.',
      mode: 'Dual',
      levelLabel: 'Current N',
      level: 2,
      accuracy: 0.84,
      bestAccuracy: 0.91,
      averageResponseMs: 612,
      streak: 5,
      badges: ['Dual unlocked', 'Latency < 650ms'],
      recommendedNext: 'Enable distraction filter',
    },
    {
      type: 'span',
      title: 'Digit & Letter Span',
      description: 'Forward and reverse span blocks tuned by SM-2 ease factors.',
      mode: 'Alternating',
      levelLabel: 'Max span',
      level: 9,
      accuracy: 0.77,
      bestAccuracy: 0.83,
      averageResponseMs: 921,
      streak: 3,
      badges: ['Reverse master'],
      recommendedNext: 'Inject 2 new sequences',
    },
    {
      type: 'pairs',
      title: 'Word-Pair Recall',
      description: 'Timed encoding + recall with semantic similarity hints.',
      mode: 'Chunked',
      levelLabel: 'Pairs mastered',
      level: 14,
      accuracy: 0.71,
      bestAccuracy: 0.8,
      averageResponseMs: 1340,
      streak: 2,
      badges: ['Context builder'],
      recommendedNext: 'Add name-face mix',
    },
    {
      type: 'grid',
      title: 'Grid Pattern Recall',
      description: 'Visual grid reproduction with interference toggles.',
      mode: '3x3',
      levelLabel: 'Patterns streak',
      level: 6,
      accuracy: 0.69,
      bestAccuracy: 0.78,
      averageResponseMs: 820,
      streak: 4,
      badges: ['Spatial streak'],
      recommendedNext: 'Switch to 4x4 once ready',
    },
    {
      type: 'srs',
      title: 'Spaced Repetition Decks',
      description: 'SM-2 like scheduling fused with FlashNote reflections.',
      mode: 'SM-2 hybrid',
      levelLabel: 'Due forecast',
      level: 48,
      accuracy: 0.92,
      bestAccuracy: 0.95,
      averageResponseMs: 2050,
      streak: 11,
      badges: ['Streak champion'],
      recommendedNext: 'Import &quot;Neuroscience&quot; deck',
    },
  ],
  analytics: {
    accuracyTrend: [
      { label: 'Mon', value: 68 },
      { label: 'Tue', value: 74 },
      { label: 'Wed', value: 79 },
      { label: 'Thu', value: 82 },
      { label: 'Fri', value: 84 },
      { label: 'Sat', value: 86 },
      { label: 'Sun', value: 88 },
    ],
    levelTrend: [
      { label: 'N-back', value: 2 },
      { label: 'Span', value: 9 },
      { label: 'Pairs', value: 14 },
      { label: 'Grid', value: 6 },
      { label: 'SRS', value: 48 },
    ],
    reactionTimes: [
      { label: 'Warmup', milliseconds: 680 },
      { label: 'Focus', milliseconds: 612 },
      { label: 'Span', milliseconds: 921 },
      { label: 'Cooldown', milliseconds: 2050 },
    ],
    forgettingCurve: [
      { day: 0, retention: 100 },
      { day: 1, retention: 92 },
      { day: 3, retention: 81 },
      { day: 5, retention: 74 },
      { day: 8, retention: 66 },
    ],
  },
  decks: [
    {
      id: 'deck-foundations',
      name: 'Cognitive Foundations',
      tag: 'Core',
      dueToday: 28,
      newCount: 5,
      totalCards: 162,
      streak: 14,
      nextDue: daysAgo(-1),
    },
    {
      id: 'deck-neuro',
      name: 'Applied Neuroscience',
      tag: 'Focus',
      dueToday: 12,
      newCount: 3,
      totalCards: 98,
      streak: 6,
      nextDue: daysAgo(-2),
    },
    {
      id: 'deck-names',
      name: 'Names & Faces',
      tag: 'Recall',
      dueToday: 8,
      newCount: 4,
      totalCards: 56,
      streak: 3,
      nextDue: daysAgo(-3),
    },
  ],
  srs: {
    activeDeckId: 'deck-foundations',
    queue: [
      {
        id: 'card-alpha',
        front: 'What is the phonological loop responsible for?',
        back: 'Holding sound-based information briefly for rehearsal.',
        easeFactor: 2.6,
        intervalDays: 4,
        dueOn: daysAgo(-1),
        lapses: 0,
      },
      {
        id: 'card-beta',
        front: 'Define dual n-back.',
        back: 'Working memory task where stimuli from two modalities are tracked in parallel.',
        easeFactor: 2.5,
        intervalDays: 3,
        dueOn: daysAgo(0),
        lapses: 1,
      },
      {
        id: 'card-gamma',
        front: 'Chunking strategy example?',
        back: 'Grouping digits like 1492-1776-2001 to expand effective span.',
        easeFactor: 2.4,
        intervalDays: 2,
        dueOn: daysAgo(1),
        lapses: 0,
      },
    ],
    completed: [],
  },
  exports: [
    {
      id: 'export-1',
      format: 'csv',
      createdAt: daysAgo(1),
      sizeKb: 48,
      includeWatermark: true,
    },
    {
      id: 'export-2',
      format: 'pdf',
      createdAt: daysAgo(4),
      sizeKb: 512,
      includeWatermark: false,
    },
  ],
});
